### ISSUE TITLE
Node_express demo throwing errors

### ISSUE THREAD

**Issue by micahgodbolt** [twigjs/twig.js#250]
After pulling down the repo, going to demo/node_express, running npm install, running node app.js then going to 0.0.0.0:9999 I get the following error

```
TypeError: Cannot read property 'rethrow' of undefined
    at Twig.parse (/Users/mgodbolt/Sites/twigtest/twig.js:614:29)
    at Twig.Template.render (/Users/mgodbolt/Sites/twigtest/twig.js:944:29)
    at Object.<anonymous> (/Users/mgodbolt/Sites/twigtest/twig.js:5393:29)
    at ServerResponse.res._render (/Users/mgodbolt/Sites/twigtest/demos/node_express/node_modules/express/lib/view.js:425:21)
    at ServerResponse.res.render (/Users/mgodbolt/Sites/twigtest/demos/node_express/node_modules/express/lib/view.js:318:17)
    at /Users/mgodbolt/Sites/twigtest/demos/node_express/app.js:76:7
    at callbacks (/Users/mgodbolt/Sites/twigtest/demos/node_express/node_modules/express/lib/router/index.js:272:11)
    at param (/Users/mgodbolt/Sites/twigtest/demos/node_express/node_modules/express/lib/router/index.js:246:11)
    at pass (/Users/mgodbolt/Sites/twigtest/demos/node_express/node_modules/express/lib/router/index.js:253:5)
    at Router._dispatch (/Users/mgodbolt/Sites/twigtest/demos/node_express/node_modules/express/lib/router/index.js:280:5)
```

node -v v0.12.6
npm -v 2.11.2

**Comment by plepe** [comment]
confirmed with node v5.5.0 and npm 3.3.12.

**Comment by dasblitz** [comment]
This happens because twig options aren't set. The code below fixes this. I've created a pull request with this update. Although it might be better to fix this inside twig and not force the user to add an empty options object.

```
app.configure(function () {
    app.use(express.static(__dirname + '/public'));
		app.use(express.bodyParser());
    app.set('views', __dirname + '/public/views');
    app.set('view engine', 'twig');
    app.set('twig options', {});
    // We don't need express to use a parent "page" layout
    // Twig.js has support for this using the {% extends parent %} tag
    app.set("view options", { layout: false });
});
```
