### ISSUE TITLE
Express 4, Webpack and Namespacing

### ISSUE THREAD

**Issue by ethyde** [twigjs/twig.js#407]
Hello,

I'm sorry to ask for that, but I try to use TwigJS with Express 4, and even after reading the documentation I am unable to define a namespace. Can you help me ? 

My server.js file : https://github.com/ethyde/StarterPack/blob/feature/SP-01/server.js
And I try to load this file : https://github.com/ethyde/StarterPack/blob/feature/SP-01/src/views/components/home/index.html.twig

Thx.

**Comment by ethyde** [comment]
Just in case , I tried without webpack and browsersync and I the following error :
```
Error parsing twig template /Users/eplouvie/Projects/Labs/StarterPack/src/views/components/home/index.html.twig:
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.statSync (fs.js:844:18)
    at Object.<anonymous> (/Users/eplouvie/Projects/Labs/StarterPack/node_modules/twig/twig.js:5389:22)
    at Object.Twig.Templates.loadRemote (/Users/eplouvie/Projects/Labs/StarterPack/node_modules/twig/twig.js:1166:24)
    at Twig.Template.importFile (/Users/eplouvie/Projects/Labs/StarterPack/node_modules/twig/twig.js:1317:48)
    at Twig.logic.definitions.parse (/Users/eplouvie/Projects/Labs/StarterPack/node_modules/twig/twig.js:6030:38)
    at Twig.logic.parse (/Users/eplouvie/Projects/Labs/StarterPack/node_modules/twig/twig.js:6611:44)
    at parseToken (/Users/eplouvie/Projects/Labs/StarterPack/node_modules/twig/twig.js:840:55)
    at Array.forEach (native)
    at Object.Twig.forEach (/Users/eplouvie/Projects/Labs/StarterPack/node_modules/twig/twig.js:151:25)
```
Server.js : https://github.com/ethyde/StarterPack/blob/4947f056dbde8d7b1d7e5be12437fbc893fe80c9/server.js

Even after uninstall & install the package.

**Comment by willrowe** [comment]
The links no longer work. If this is still an issue, please re-open with a simplified example to reproduce.
