### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by mongreldogg** [twigjs/twig.js#595]
Following a guideline, I have installed Twig on NPM 6.4.1 / Node 8.12.0:

`npm install twig --save`

Issue in a code part:

`var twig = require('twig').twig();`

Same as attempted:

```
var twig = require('twig').twig;
twig().render('Hello, {{ world }}', { world: 'World!' });
```

Error log:

`TypeError: Cannot read property 'id' of undefined
    at Object.e.exports.twig (C:\www\merchant_portal\node_modules\twig\twig.js:1:3188)
    at Object.<anonymous> (C:\www\merchant_portal\index.js:1:90)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3`

Please advice.

**UPD**:

Tried another method described:

`import Twig from 'twig';`

And got this:

```
(function (exports, require, module, __filename, __dirname) { import Twig from 'twig';

                       ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
```

Also, if it makes any sense to mention it - I am trying on Windows 7 Ultimate x64 with NodeJS of the same target architecture installed. Just in case

**Comment by ericmorand** [comment]
Where did you find that guildeline?

I usually use Twig.js this way:

```
let Twig = require('twig');

let template = Twig.twig({
                path: 'templates/index.html.twig',
                async: false,
                autoescape: true
            });

return template.render(data);
```
