### ISSUE TITLE
twigjs cli broken in 1.14.0

### ISSUE THREAD

**Issue by fatmuemoo** [twigjs/twig.js#684]
twigjs cli is broken in 1.14.0

Steps to reproduce:

`$ npm install twig -g`

```
/usr/bin/twigjs -> /usr/lib/node_modules/twig/bin/twigjs
/usr/lib
└─┬ twig@1.14.0 
  └─┬ @babel/runtime@7.7.4 
    └── regenerator-runtime@0.13.3 

$ twigjs
/usr/lib/node_modules/twig/twig.js:1427
            ...blocks,
            ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/twig/lib/compile.js:4:14)
$ npm install twig -g
/usr/bin/twigjs -> /usr/lib/node_modules/twig/bin/twigjs
/usr/lib
└── twig@1.14.0 

$ twigjs
/usr/lib/node_modules/twig/twig.js:1427
            ...blocks,
            ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/twig/lib/compile.js:4:14)
```

Installing older version it works as expected:

`$ npm install twig@1.13.3 -g`
```
/usr/bin/twigjs -> /usr/lib/node_modules/twig/bin/twigjs
- regenerator-runtime@0.13.3 node_modules/twig/node_modules/regenerator-runtime
- @babel/runtime@7.7.4 node_modules/twig/node_modules/@babel/runtime
/usr/lib
└── twig@1.13.3 

$ twigjs
ERR: No input files provided

Usage:
	twigjs [options] input.twig | directory ...
	_______________________________________________________________________________

	twigjs can take a list of files and/or a directories as input. If a file is
	provided, it is compiled, if a directory is provided, all files matching *.twig
	in the directory are compiled. The pattern can be overridden with --pattern

	--help         Print this help message.

	--output ...   What directory should twigjs output to. By default twigjs will
	               write to the same directory as the input file.

	--module ...   Should the output be written in module format. Supported formats:
	                   node:  Node.js / CommonJS 1.1 modules
	                   amd:   RequireJS / Asynchronous modules (requires --twig)
	                   cjs2:  CommonJS 2.0 draft8 modules (requires --twig)

	--twig ...     Used with --module. The location relative to the output directory
	               of twig.js. (used for module dependency resolution).

	--pattern ...  If parsing a directory of files, what files should be compiled.
	               Defaults to *.twig.

NOTE: This is currently very rough, incomplete and under development.
```

**Comment by madflow** [comment]
This error occurs when the NodeJS version is `6` when I test it. The `engines` field in package.json states `">=6.0"`. The Travis build does not test NodeJS `6`. 

What is the official minimal supported version?

**Comment by RobLoach** [comment]
I believe it's 10 at this point. While I've stuck it to 8.16, Node <=10 is no longer supported. The twig.js file may support it, but I'll leave that determination to you.
